name: Hello World workflow

on:
  push:
   branches:
     dev
  pull_request:
    branches:
      dev
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker version
        run: docker --version
  
